FROM golang:latest

# Cloning netman release repo
WORKDIR /
RUN git clone --recursive https://github.com/cloudfoundry-incubator/netman-release.git

# Installing cf cli
RUN mkdir /cf-cli
ADD https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.21.1 cf-cli_6.21.1_linux_x86-64.tgz
RUN tar -xvzf cf-cli_6.21.1_linux_x86-64.tgz -C /cf-cli
ENV PATH=/cf-cli:$PATH

# Building netman release from sources
WORKDIR /netman-release/src/cli-plugin
ENV GOPATH /netman-release 
RUN go build -o /tmp/network-policy-plugin 

# Installing the plugin
RUN chmod +x /tmp/network-policy-plugin
RUN cf install-plugin -f /tmp/network-policy-plugin

